FROM golang:1.22.3-bullseye

WORKDIR /

RUN apt-get update && \
    apt-get -y upgrade


# Build Utilities

RUN apt-get install -y curl jq git podman

# Cleanup

RUN rm -rf ${GOPATH}/src/*

RUN apt-get clean && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/*
